import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineNewspaper,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiTypescript,
  SiAmazonwebservices,
  SiGooglecloud,
  SiPython,
  SiR,
  SiCplusplus,
  SiHtml5,
  SiCss3,
  SiGo,
  SiRust,
  SiOpenjdk,
  SiRuby,
  SiDart,
  SiPostgresql,
  SiTailwindcss,
  SiShadcnui,
  SiFramer,
  SiGreensock,
  SiThreedotjs,
  SiReactquery,
  SiNodedotjs,
  SiExpress,
  SiFastify,
  SiFastapi,
  SiRubyonrails,
  SiSocketdotio,
  SiJsonwebtokens,
  SiClerk,
  SiExpo,
  SiFlutter,
  SiFirebase,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiDrizzle,
  SiPrisma,
  SiUpstash,
  SiCloudinary,
  SiAmazons3,
  SiPandas,
  SiNumpy,
  SiScikitlearn,
  SiLangchain,
  SiGooglegemini,
  SiJupyter,
  SiPlotly,
  SiTableau,
  SiDocker,
  SiGithubactions,
  SiVercel,
  SiRender,
  SiLinux,
  SiGnubash,
  SiGin,
  SiApachemaven,
  SiJunit5,
  SiBluetooth,
  SiCmake,
  SiOpenssl,
  SiGooglesheets,
  SiSqlalchemy,
  SiZod,
  SiYoutube,
  SiWayland,
  SiArchlinux,
  SiVim,
  SiScipy,
  SiTurborepo,
  SiPuppeteer,
  SiJest,
  SiMongoose,
  SiReactrouter,
} from "react-icons/si";

import { VscAzure } from "react-icons/vsc";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  newspaper: HiOutlineNewspaper,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  react: SiReact,
  typescript: SiTypescript,
  aws: SiAmazonwebservices,
  azure: VscAzure,
  googlecloud: SiGooglecloud,
  python: SiPython,
  r: SiR,
  cplusplus: SiCplusplus,
  html5: SiHtml5,
  css3: SiCss3,
  go: SiGo,
  rust: SiRust,
  java: SiOpenjdk,
  ruby: SiRuby,
  dart: SiDart,
  postgresql: SiPostgresql,
  tailwind: SiTailwindcss,
  shadcn: SiShadcnui,
  framer: SiFramer,
  gsap: SiGreensock,
  threejs: SiThreedotjs,
  reactquery: SiReactquery,
  nodejs: SiNodedotjs,
  express: SiExpress,
  fastify: SiFastify,
  fastapi: SiFastapi,
  rails: SiRubyonrails,
  socketio: SiSocketdotio,
  jwt: SiJsonwebtokens,
  clerk: SiClerk,
  expo: SiExpo,
  flutter: SiFlutter,
  firebase: SiFirebase,
  mongodb: SiMongodb,
  redis: SiRedis,
  sqlite: SiSqlite,
  drizzle: SiDrizzle,
  prisma: SiPrisma,
  upstash: SiUpstash,
  cloudinary: SiCloudinary,
  amazons3: SiAmazons3,
  pandas: SiPandas,
  numpy: SiNumpy,
  scikitlearn: SiScikitlearn,
  langchain: SiLangchain,
  gemini: SiGooglegemini,
  jupyter: SiJupyter,
  plotly: SiPlotly,
  tableau: SiTableau,
  docker: SiDocker,
  githubactions: SiGithubactions,
  vercel: SiVercel,
  render: SiRender,
  linux: SiLinux,
  bash: SiGnubash,
  gin: SiGin,
  maven: SiApachemaven,
  junit: SiJunit5,
  bluetooth: SiBluetooth,
  cmake: SiCmake,
  openssl: SiOpenssl,
  googlesheets: SiGooglesheets,
  sqlalchemy: SiSqlalchemy,
  zod: SiZod,
  youtube: SiYoutube,
  wayland: SiWayland,
  archlinux: SiArchlinux,
  vim: SiVim,
  scipy: SiScipy,
  turborepo: SiTurborepo,
  puppeteer: SiPuppeteer,
  jest: SiJest,
  mongoose: SiMongoose,
  reactrouter: SiReactrouter,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
